language: elixir
elixir:
  - '1.6.1'
otp_release:
  - '20.1'
nodejs:

cache:
  directories:
    - ~/.mix
    - ~/.hex
    - deps
    - _build
    - ~/.cache/yarn

addons:
  chrome: stable

before_install:
 - sudo apt-get install chromium-chromedriver

before_script:
 - MIX_ENV=test mix compile
 - cd ./assets;
 - yarn
 - ./node_modules/brunch/bin/brunch b -p ;
 - cd ../;
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 # give xvfb some time to start
 - "export PATH=$PATH:/usr/lib/chromium-browser/"
 - nohup chromedriver &

# Travis build matrix; run these two in parallel, so that we have early feedback on normal tests,
# but also run integration tests.
env:
  - TEST_SUITE=""
  - TEST_SUITE="--only integration:true"

script: "mix test $TEST_SUITE"

jobs:
  include:
    - stage: format
      env:
        - MIX_ENV=dev
      script: mix format --check-formatted
